### ISSUE TITLE
Add "All Locations" Map Shortcode

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/wp-simple-locator#34]
May be helpful to have a shortcode that displays a map with all locations.

**Comment by plugza** [comment]
Is there a workaround solution to show all locations and zoom out right now?

**Comment by kylephillips** [comment]
I can't think of a workaround currently, but this is something I'm working on now. It should be available in the next release.

**Comment by plugza** [comment]
Thanks for responding. :+1:
Next question
Is there any solution to use search by country?

**Comment by kylephillips** [comment]
v1.1.0, just released, includes a shortcode for showing a map with all locations, zoomed to fit.
The shortcode is [simple_locator_all_locations].

There is no way currently to limit searches by country. The input uses Google Maps' API to geocode searches, so if someone did want to search by countries, they could enter that country.
