### ISSUE TITLE
Uncaught ReferenceError: wpsl_locator is not defined

### ISSUE THREAD

**Issue by plugza** [kylephillips/wp-simple-locator#35]
When I use [simple_locator_all_locations]
the loading keeps spinning.
And debugger show this
```
Uncaught ReferenceError: wpsl_locator is not defined
simple-locator-all-locations.js:1
```
But [wp_simple_locator] works fine.

**Comment by kylephillips** [comment]
This should be cleared up in v1.1.2, just released. There was a script that wasn't being enqueued.

**Comment by plugza** [comment]
After update I got this.

```Uncaught ReferenceError: data is not defined
simple-locator-all-locations.js:1```
