### ISSUE TITLE
Search by place name and some issues

### ISSUE THREAD

**Issue by plugza** [kylephillips/wp-simple-locator#42]
Is there any way to search the place by name?

And some issues i've found.
- I can search by some country name but some of them don't.
Example:
I have one place in my database is Dhaka, Bangladesh. I searched 'Bangladesh' I found Dhaka.
But I have places in Bangkok, Thailand. I searched 'Thailand' or 'Thai' I got 0 result found.

**Comment by kylephillips** [comment]
v1.3.0 includes an option to enable Google Places autocomplete on the search form. This may help in your case.
