### ISSUE TITLE
Does it need a specific permalink structure?

### ISSUE THREAD

**Issue by lmartins** [kylephillips/wp-simple-locator#50]
Hi Kyle,

Im having issues displaying the built-in "locations" post-type, always results in 404. 
Im building a list of "location" posts, but even if I link an entry directly to a menu, it still goes 404.

Any tips please?
Thanks.

**Comment by lmartins** [comment]
Oh, never mind. 
After 2 hours it started working. Don't ask me why...

**Comment by kylephillips** [comment]
I'll double check that permalinks are being flushed on activation… if not, then that's the source of the problem.
