### ISSUE TITLE
Search by Country and Zip Code Issues

### ISSUE THREAD

**Issue by lmartins** [kylephillips/wp-simple-locator#51]
Hey Kyle,

A few questions about the search feature on the default form widget.
Im trying to implement a simple business directory using your plugin. This directory has entries from multiple countries, so search by country is quite important. Unfortunately the default search widget doesn't seem to do it, as searching by the country name always returns no results.

Another quick question, if I pass `resultscontainer="#searchresults"`, shouldn't the dom elements inside that `div` be replaced with the results from my search?

Update:
Adding to the problem searching by country, im noticing that searching by zip-code is also giving unexpected results.

I have this entry with the zip code value of `1100-200`, if I search by this exact same value it retrieves no results found, no matter what distance I pass it. This is the portuguese zip code format, does the plugin allow to use non-US zip codes?

Thanks again for any help.

**Comment by kylephillips** [comment]
The search form uses the Google Maps Geocode API to convert the input into coordinates. The coordinates are then passed to the plugin to perform the search. 

The next release will include the option of enabling Google Maps Autocomplete on the search form. Hopefully this will clear up some of the search issues by providing a list of choices for users to select from as they type.

If you're using the shortcode, then yes, passing that resultscontainer parameter should load the results into it. It's how the demo site is setup.
