### ISSUE TITLE
Loop aware All Locations Map

### ISSUE THREAD

**Issue by lmartins** [kylephillips/wp-simple-locator#52]
If I understand this correctly, the map will always retrieve all entries from the selected post-type. Would it be possible to have the map to show only the entries on screen?

Im building a business directory, for which im displaying all entries in a loop, paginated with 24 records per page. The ideia would be to have the map match the records displayed on screen, being updated at each page change.

This might outside the scope of the plugin's original intent, but it might greatly extend the plugin uses cases with what I imagine wouldn't be a too complex change.

Anyway i'll study the code to see if can achieve this, hopefully you can provide your insight here.

**Comment by kylephillips** [comment]
Closing this issue… rolling it into this enhancement issue:
https://github.com/kylephillips/wp-simple-locator/issues/54
