### ISSUE TITLE
Geocode values stay empty with Custom Post Type (not the built-in Locations post-type)

### ISSUE THREAD

**Issue by lmartins** [kylephillips/wp-simple-locator#53]
When you assign a custom post type to the plugin, it adds the location field to that post-type, which is nice, the problem is that the Geocode values will stay empty as you can see here:
http://snpy.link/qoLL2A

Ideally the fields should be hidden or populated with the data provided by the post.

Cheers.

**Comment by kylephillips** [comment]
Couple things:
* The bug preventing the Geo fields from saving on CPTs is fixed and will be in the next release.
* The next release will also include the option to hide the included custom fields
* Related to above, it will also support ACF Google Map fields, which it looks like you're using in your screenshot

**Comment by lmartins** [comment]
Great news!
If I download the github version will I be able to test the new features?
Perhaps I could help giving some feedback and providing translation for PT.

Thanks again Kyle.

**Comment by kylephillips** [comment]
You could download the github version, but if you do, make sure to run `composer install`. Otherwise the autoloader won't be included and the plugin will fail to activate.

**Comment by lmartins** [comment]
Hi Kyle,

Tried that but got an error:
```
Loading composer repositories with package information
Installing dependencies (including require-dev)



  [RuntimeException]
  Could not load package guzzlehttp/guzzle in http://packagist.org: [UnexpectedValueException] Could not parse versio
  n constraint ^1.1: Invalid version string "^1.1"






  [UnexpectedValueException]
  Could not parse version constraint ^1.1: Invalid version string "^1.1"



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
```

Will wait for the release, also because I can't get the search to output anything no matter what I try.
