### ISSUE TITLE
Parse error: syntax error, unexpected '[', expecting ')' 

### ISSUE THREAD

**Issue by plugza** [kylephillips/wp-simple-locator#56]
Just updated the latest version and get this

```
Parse error: syntax error, unexpected '[', expecting ')' in ***/wp-content/plugins/simple-locator/vendor/react/promise/src/functions.php on line 68
```

**Comment by jaredkc** [comment]
I had the same problem. It was due to my server using an older version of PHP. The latest Simple Locator version requires PHP 5.4+.

**Comment by mbube2** [comment]
I have the same problem:
Parse error: syntax error, unexpected '[', expecting ')' in C:\wamp\www\ci_bootstrap_3\application\vendor\react\promise\src\functions.php on line 68

A PHP Error was encountered
Severity: Parsing Error

Message: syntax error, unexpected '[', expecting ')'

Filename: src/functions.php

Line Number: 68

Backtrace:
