### ISSUE TITLE
Singular View Shortcode Bug

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/wp-simple-locator#59]
Need to add simple-locator to array of dependencies when enqueueing single view scripts. (enqueueScripts method in API\SingleLocationShortcode)

**Comment by anjit** [comment]
I enqueued the "google-maps" js in the SingleLocationShortcode and after that performed some changes in the assets js file "simple-locator-single.js" i.e:

changed all wpsl_locator to wpsl_locator_single and after that its working for me.

**Comment by anjit** [comment]
Can you do some change in search like if anyone search the address than it will show popup marker with the result.
