### ISSUE TITLE
Programmatically update geocode values

### ISSUE THREAD

**Issue by nicolasmn** [kylephillips/wp-simple-locator#63]
I want to geocode a bunch of posts without going through saving each of it one by one. I tried to use `do_action( 'save_post', $post_id )` but no luck, how can I do it?

**Comment by jaredkc** [comment]
+1, I would love to how to do this also

**Comment by kylephillips** [comment]
There isn't a way to geocode existing posts programmatically. There is however a CSV importer to create and geocode new posts in bulk, located in the plugin settings.

There are so many different customization options when it comes to how fields are saved, it would be quite involved to build out a way to do that programmatically.

**Comment by nicolasmn** [comment]
The problem is that the CSV importer provided isn't very flexible.
Currently I'm using WP All Import to import categories together with the
other location information and I need a way to geocode these imports.
Kyle Phillips <notifications@github.com> schrieb am Mi., 9. Sep. 2015 um
17:10:

**Comment by nicolasmn** [comment]
For anyone interested I found this gist which works just fine: https://gist.github.com/verticalgrain/7f377bbf857766f76193
