### ISSUE TITLE
Form with all locations as default view

### ISSUE THREAD

**Issue by elihorn** [kylephillips/wp-simple-locator#69]
It would be nice to show all the locations as a default map view, in addition to the search form. Is this possible using one of the available shortcodes?

**Comment by kylephillips** [comment]
This is possible by using the `[simple_locator_all_locations]` shortcode.

**Comment by elihorn** [comment]
Thanks for the quick response @kylephillips though I don't see a way to include the ZIP/Address search form using the `[simple_locator_all_locations]` shortcode

**Comment by elihorn** [comment]
I'm not sure this is the best way to do it, but it seems to work using the two shortcodes together like this:

    [wp_simple_locator mapcontainer="#alllocationsmap"]
    [simple_locator_all_locations]
