### ISSUE TITLE
Class 'SimpleLocator\Bootstrap' not found in SimpleLocator.php on line 17

### ISSUE THREAD

**Issue by anastasialanz** [kylephillips/wp-simple-locator#73]
I get this error after installing. Any idea on how to fix this or what could be causing it?

I have "wpackagist-plugin/simple-locator": "1.5.2" installed running WP 4.5.3

**Comment by kylephillips** [comment]
If you're installing from this repo, you'll need to run a composer install, and the directory needs to be named "wp-simple-locator".

If you're installing from the WP repository, make sure you're using PHP version 5.3+.

**Comment by anastasialanz** [comment]
Still having the same issue even when renaming the directory.

**Comment by kylephillips** [comment]
I'm not familiar with WP Packagist… perhaps try running `composer dump-autoload`.

**Comment by Santana1053** [comment]
I am getting this error using PHP 7.1 when I run `wp theme activate` with WP-CLI

**Comment by Nicscott01** [comment]
Seems that this still happens with PHP 8. Seems to be an autoloader issue and things not being happy when on the wp-cli. I haven't figured out a fix yet, however. Any insight is appreciated.
